# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            raemadeline
tagline:          'blog'
description:      'A collection of my recent projects and thoughts about tech'
url:              http://raemadeline.github.io/blog
baseurl:          /

author:
  name:           'Madeline Rae Horowitz'
  url:            https://raemadeline.com

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/raemadeline/blog

gems: [jekyll-paginate, redcarpet, jekyll-gist, pygments.rb]
